# Generated by Django 2.0.2 on 2018-11-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categeory_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkind',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categeory_book_app.BookKind'),
        ),
    ]
