# Generated by Django 2.0.2 on 2018-11-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categeory_book_app', '0002_auto_20181116_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookkind',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
