# Generated by Django 2.0.2 on 2018-11-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_kind',
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('print_time', models.DateField(blank=True, null=True)),
                ('print_times', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=100, null=True)),
                ('word_num', models.CharField(blank=True, max_length=100, null=True)),
                ('page_num', models.CharField(blank=True, max_length=100, null=True)),
                ('page_size', models.CharField(blank=True, max_length=100, null=True)),
                ('paper', models.CharField(blank=True, max_length=100, null=True)),
                ('packing', models.CharField(blank=True, max_length=100, null=True)),
                ('mark_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('dangdang_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('series_name', models.CharField(blank=True, max_length=100, null=True)),
                ('editor_recommendation', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('introduce_author', models.CharField(blank=True, max_length=100, null=True)),
                ('media', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_book', models.CharField(blank=True, max_length=100, null=True)),
                ('ground_time', models.DateTimeField(blank=True, null=True)),
                ('off_time', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('sales_volume', models.IntegerField(blank=True, null=True)),
                ('recommend', models.IntegerField(blank=True, null=True)),
                ('cus_score', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('sale', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('book_count', models.IntegerField(blank=True, null=True)),
                ('del_field', models.IntegerField(blank=True, db_column='del', null=True)),
                ('finish', models.IntegerField(blank=True, null=True)),
                ('finish_times', models.IntegerField(blank=True, null=True)),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user_app.TBook')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.AddField(
            model_name='tbook',
            name='book_kind',
            field=models.ForeignKey(blank=True, db_column='book_kind', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.BookKind'),
        ),
        migrations.AddField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.TUser'),
        ),
        migrations.AddField(
            model_name='torder',
            name='addrees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.TAddress'),
        ),
        migrations.AddField(
            model_name='torder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.TUser'),
        ),
    ]
